### ISSUE TITLE
On Logout: TypeError: undefined is not an object (evaluating 'userData.firstName')

### ISSUE THREAD

**Issue by sohomsaha1** [sohomsaha1/Immigrate-ai-app#18]
Error on Logout, presumably due to Onboarding data not being set properly so the Profile refresh on click "Login" breaks the page.

Possible fix: Check why the name is not  set
![Screen Shot 2022-03-22 at 2 42 15 PM](https://user-images.githubusercontent.com/57738616/159552985-c3af753d-12a6-4a14-ac59-be2281666c05.png)

**Comment by DevinLeamy** [comment]
Done. Will be in the next PR.
