### ISSUE TITLE
Phone number is as 'PLACEHOLDER' for onboarding page

### ISSUE THREAD

**Issue by sohomsaha1** [sohomsaha1/Immigrate-ai-app#21]
Dependency: Issue #20 -> We need a valid phone number

Issue: Profile page shows default placeholder, needs to be updated from registration information.

Possible Solution: Once we have 2FA setup any phone number which is verified will be linked to the corresponding user

**Comment by DevinLeamy** [comment]
Done. Will be in the next PR.
