### ISSUE TITLE
Progress Context needed for users

### ISSUE THREAD

**Issue by sohomsaha1** [sohomsaha1/Immigrate-ai-app#43]
![Screen Shot 2022-03-31 at 10 04 59 AM](https://user-images.githubusercontent.com/57738616/161074218-57e59cbd-d00e-4a50-8e98-124532f32388.png)

Basically we want to store the progress of the users based on what they do on the app.

1) "Find your new home" -> Simply updates when users navigate to the blogs once they click the arrow

2) "Determine elegibility" -> Once users either finish provincial or federal eligibility check they will get past this progress step. 

3) Connect with an agent -> Leave todo for now

**Comment by DevinLeamy** [comment]
Do we need this anymore? @sohomsaha1

**Comment by sohomsaha1** [comment]
> Do we need this anymore? @sohomsaha1

No closing issue
